char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - lshoulder
  - lelbow
  - lhand
  - metacarpal3.l
  - rshoulder
  - relbow
  - rhand
  - metacarpal3.r
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - lhip
  - lknee
  - lfoot
  - LeftToeBase
  - rhip
  - rknee
  - rfoot
  - RightToeBase
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - hip
  - abdomen
  - chest
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - hip
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - lhand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - rhand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - lfoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - rfoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - rfoot
    - rknee
    - rhip
  - - lfoot
    - lknee
    - lhip
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - lshoulder
  - lelbow
  left_foot: !!python/tuple
  - lknee
  - lfoot
  left_hand: !!python/tuple
  - lelbow
  - lhand
  left_knee: !!python/tuple
  - lhip
  - lknee
  torso: !!python/tuple
  - hip
  - chest
  neck: !!python/tuple
  - hip
  - Head
  right_elbow: !!python/tuple
  - rshoulder
  - relbow
  right_foot: !!python/tuple
  - rknee
  - rfoot
  right_hand: !!python/tuple
  - relbow
  - rhand
  right_knee: !!python/tuple
  - rhip
  - rknee
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder