scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char2/char_cfg.yaml
      motion_cfg: examples/config/motion/mocap_output.yaml
      retarget_cfg: examples/config/retarget/mocap_retarget.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ../SharedVolume/video.gif